.ruby: &ruby
  env:
    ## https://github.com/docker-library/ruby/issues/45
    LANG: C.UTF-8
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME:$CIRRUS_OS
      - ruby -v
      - cat Gemfile
    populate_script: bundle update

remark_task:
  container:
    image: node:latest
  node_modules_cache:
    folder: node_modules
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME:$CIRRUS_OS
      - node -v
      - cat package.json
    populate_script: yarn install
  remark_script: yarn run remark

rubocop_task:
  <<: *ruby
  container:
    image: ruby:latest
  rubocop_script: bundle exec rubocop
