test_task:
  container:
    matrix:
      image: ruby:2.4
      image: ruby:2.5
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_TASK_NAME:$CIRRUS_OS
      - ruby -v
      - cat Gemfile
      - cat **/*.gemspec
    populate_script: bundle update
  test_script: bundle exec rake
