AllCops:
  TargetRubyVersion: 2.4

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/EmptyLinesAroundArguments:
  Exclude:
    - r18n-core/locales/*.rb

Naming/FileName:
  Exclude:
    - 'r18n-core/locales/*.rb'
    - 'r18n-core/spec/locales/*.rb'
    - '**/r18n-core.rb'
    - '**/r18n-rails.rb'
    - '**/r18n-rails-api.rb'
    - '**/r18n-desktop.rb'
    - '**/r18n-desktop_spec.rb'
    - '**/sinatra-r18n.rb'
    - '**/sinatra-r18n_spec.rb'

Style/AsciiComments:
  Enabled: false

Style/FormatStringToken:
  Enabled: false # https://github.com/bbatsov/rubocop/issues/5398

Style/DateTime:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - 'benchmark/*'

Style/Documentation:
  Exclude:
    - '**/spec/**/*'

Style/NumericLiterals:
  Exclude:
    - '**/db/**/*'
