require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  # - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

inherit_mode:
  merge:
    - Include
    - Exclude

Naming/FileName:
  Exclude:
    - 'r18n-core/lib/r18n-core/locales/*.rb'
    - 'r18n-core/spec/locales/*.rb'
    - '**/r18n-core.rb'
    - '**/r18n-rails.rb'
    - '**/r18n-rails-api.rb'
    - '**/r18n-desktop.rb'
    - '**/r18n-desktop_spec.rb'
    - '**/sinatra-r18n.rb'
    - '**/sinatra-r18n_spec.rb'

Style/AsciiComments:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - 'benchmark/*'

Style/NumericLiterals:
  Exclude:
    - '**/db/**/*'

Rails/RakeEnvironment:
  Enabled: false

Rails/TimeZone:
  Exclude:
    - benchmark/**/*
    - r18n-core/**/*
    - r18n-desktop/**/*
    ## https://github.com/rubocop-hq/rubocop-rails/issues/432
    - '**/*.gemspec'

Rails/Date:
  Exclude:
    - r18n-core/**/*

Rails/NegateInclude:
  Exclude:
    - benchmark/**/*

# TODO: fix offenses and enable cops

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false
  Exclude:
    - '**/spec/**/*'
